/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pruebas;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tati
 */
public class prueba extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    
    DefaultTableModel modeloTabla ;
    DefaultListModel<String> modeloLista;
    int vector [] = {1,2,3,4,5,6,7,8,9,10};
    
    public prueba() {
        initComponents();
        inicializarTabla();
        inicializarLista();
        
        cargarCombo();
    }
    
    
    public void inicializarTabla (){
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Pare");
        modeloTabla.addColumn("Impares");
        jtblClasificacion.setModel(modeloTabla);
    }
    
    public void inicializarLista (){
        modeloLista = new DefaultListModel<>();
        jlstResultado.setModel(modeloLista);
    }
    
    private void cargarCombo(){
        jcbxSeleccionarNumero.removeAllItems();
        jcbxSeleccionarNumero.addItem("Seleccione");
        for (int i = 0; i < vector.length; i++) {
            jcbxSeleccionarNumero.addItem(String.valueOf(vector[i]));
        }
        jcbxSeleccionarNumero.setSelectedIndex(0);
    }
     
    
    
     private void procesarSeleccion() {
        
         if (jcbxSeleccionarNumero.getSelectedItem() == null) {
            return;
        }

        if (jcbxSeleccionarNumero.getSelectedIndex() <= 0) {
            return;
        }

        int numero = Integer.parseInt(jcbxSeleccionarNumero.getSelectedItem().toString());

        if (numeroYaExiste(numero)) {
            JOptionPane.showMessageDialog(this, "Número repetido");
            return;
        }

        agregarATabla(numero);
        agregarALista(numero);
    }

    private boolean numeroYaExiste(int numero) {
        for (int i = 0; i < jtblClasificacion.getRowCount(); i++) {
            Object par = jtblClasificacion.getValueAt(i, 0);
            Object impar = jtblClasificacion.getValueAt(i, 1);

            boolean existeEnPar = par != null && par.toString().equals(String.valueOf(numero));
            boolean existeEnImpar = impar != null && impar.toString().equals(String.valueOf(numero));

            if (existeEnPar || existeEnImpar) {
                return true;
            }
        }
        return false;
    }

    private void agregarATabla(int numero) {
        Object[] fila = (numero % 2 == 0) ? new Object[]{numero, ""} : new Object[]{"", numero};
        modeloTabla.addRow(fila);
    }

    private void agregarALista(int numero) {
        String texto = (numero % 2 == 0) ? numero + " Par" : numero + " Impar";
        modeloLista.addElement(texto);
    }

    private void limpiarTodo() {
        modeloTabla.setRowCount(0);
        modeloLista.clear();
        jcbxSeleccionarNumero.setSelectedIndex(0);
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblSeleccionDeNumero = new javax.swing.JLabel();
        jlblClasificacion = new javax.swing.JLabel();
        jcbxSeleccionarNumero = new javax.swing.JComboBox<>();
        jbtnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstResultado = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblClasificacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblSeleccionDeNumero.setText("Selecione un numero ");

        jlblClasificacion.setText("Clasificacion");

        jcbxSeleccionarNumero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbxSeleccionarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxSeleccionarNumeroActionPerformed(evt);
            }
        });

        jbtnLimpiar.setText("Limpiar");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jlstResultado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlstResultado);

        jLabel1.setText("Resultado");

        jtblClasificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtblClasificacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblSeleccionDeNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jcbxSeleccionarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jbtnLimpiar)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlblSeleccionDeNumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbxSeleccionarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblClasificacion)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jbtnLimpiar)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbxSeleccionarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxSeleccionarNumeroActionPerformed
        // TODO add your handling code here:
        procesarSeleccion();
    }//GEN-LAST:event_jcbxSeleccionarNumeroActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarTodo();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JComboBox<String> jcbxSeleccionarNumero;
    private javax.swing.JLabel jlblClasificacion;
    private javax.swing.JLabel jlblSeleccionDeNumero;
    private javax.swing.JList<String> jlstResultado;
    private javax.swing.JTable jtblClasificacion;
    // End of variables declaration//GEN-END:variables
}
